global using Furion.DynamicApiController;
global using Furion.FriendlyException;
global using Mapster;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.CodeAnalysis;
global using SqlSugar;
global using System.Text.Json.Serialization;
global using XsoaApi.Core;
global using XsoaApi.Core.Models;
